name: flutter_advanced_avatar_example
description: Demonstrates how to use the flutter_advanced_avatar plugin.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_advanced_avatar:
    path: ../

flutter:
  uses-material-design: true

  assets:
     - assets/images/
