name: flutter_advanced_avatar
description: An advanced avatar provides a rich API for widget customization that opens a new look and feel in your app.
version: 1.5.0
homepage: https://github.com/alex-melnyk/flutter_advanced_avatar
repository: https://github.com/alex-melnyk/flutter_advanced_avatar
issue_tracker: https://github.com/alex-melnyk/flutter_advanced_avatar/issues
documentation: https://github.com/alex-melnyk/flutter_advanced_avatar/blob/master/README.md

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter: