name: Publish to pub.dev

on:
  release:
    types: [published]

jobs:
  publish:
    permissions:
      pull-requests: write
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
    with:
      use-flutter: true